name: onlinemovieplatform
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  animate_do: ^3.3.4
  http: ^1.2.2
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  flutter_custom_clippers: ^2.1.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  google_sign_in_android: ^6.1.0
  google_sign_in_ios: ^5.7.0
  google_sign_in_platform_interface : ^2.4.0
  google_sign_in_web : ^0.12.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/intro/movieicon.png
    - assets/images/intro/download.png
    - assets/images/intro/time.png
    - assets/images/actors/henrycavill.jpg
    - assets/images/actors/benafflec.jpg
    - assets/images/actors/scarlet.jpg
    - assets/images/actors/sylvester.jpg


  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
        # - asset: fonts/Vazir-Bold.ttf